services:
  - type: web
    name: template-generator
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app -c gunicorn.conf.py
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: False
      - key: GEMINI_API_KEY
        sync: false
      - key: SCRAPING_DELAY_MIN
        value: 1
      - key: SCRAPING_DELAY_MAX
        value: 3
      - key: MAX_PAGES
        value: 2